### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by LordMaxxie** [OhhLoz/HoneyPlus#10]
Maybe I'm missing something.
But putting the files in Valheim\BepInEx\plugins doesn't do it.
Have all the pre-requisites. Opening up the cauldron - nothing there.

**Comment by OhhLoz** [comment]
Hey, I believe with manual installs the folder needs to be called "OhhLoz-HoneyPlus" because that's what thunderstore uses. This is only present in version 2. I can see about making it platform independent and if not then add that note to the readme
