### ISSUE TITLE
Food name and description not loaded if game client language is other than english

### ISSUE THREAD

**Issue by Array-D** [OhhLoz/HoneyPlus#11]
![Screenshot_690](https://user-images.githubusercontent.com/85421801/120909926-08778c80-c683-11eb-854a-c931d0deec10.png)
I'm not asking for translation, just a way to load i18n.json values into the game with different client languages would be great.

**Comment by OhhLoz** [comment]
Hey thanks for the bug report, I'll get on that ASAP. Not sure why that would be but it sounds interesting.

**Comment by OhhLoz** [comment]
It should be fixed in 2.0.1, thanks for using my mod & helping with development!

**Comment by Array-D** [comment]
thank you for the fix, love your mod)

**Comment by OhhLoz** [comment]
thanks man, means alot
