### ISSUE TITLE
Suggestion - Server recipe.json Sync

### ISSUE THREAD

**Issue by virtualbjorn** [OhhLoz/HoneyPlus#12]
Does the mod already support this?

**Comment by OhhLoz** [comment]
Hi,
Not quite sure what you mean by this, I'm assuming you mean having a server recipes.json to avoid users adding in their own items in their clientside json?

**Comment by virtualbjorn** [comment]
Is it possible to have this implemented so the client will always use the recipe.json from the server while they are connected?

**Comment by baruchvlz** [comment]
It is possible, especially with . If it's ok with @OhhLoz I can take a look at it.

**Comment by OhhLoz** [comment]
@baruchvlz sure, I would have no idea where to start apart from seeing how other mods handle it

**Comment by baruchvlz** [comment]
@OhhLoz Well, I take back what I said. I'm not sure if this is possible because the recipes are loaded into the game before any contact to the server is made.

**Comment by OhhLoz** [comment]
ValheimPlus had some consistency checks so maybe its possible? I would have to see how they handle it

**Comment by virtualbjorn** [comment]
One of the mods that implement server JSON config is EpicLoot.

Also it may also be possible with .cfg instead of a JSON file. But that may take too much of your time.

**Comment by baruchvlz** [comment]
> ValheimPlus had some consistency checks so maybe its possible? I would have to see how they handle it

They have a configuration sync which is easy to do with a RPC relay. 

> One of the mods that implement server JSON config is EpicLoot.

@virtualbjorn I don't think this is true, I've used EpicLoot before and there is no item definition sync between server and client. 

---

The recipes are loaded into the game when the game starts, there is no way to change the recipes during runtime.

**Comment by virtualbjorn** [comment]
You must not have tried editing json files for EpicLoot which me and my community do for the server without even editing any client json files.

**Comment by baruchvlz** [comment]
@virtualbjorn Of course you can edit the JSON files for the server, this doesn't mean they are synced with the client.

**Comment by virtualbjorn** [comment]
lol, I don't know why you're saying that they aren't being synced to the clients. THEY ARE SYNCING that's what I'm saying as someone who manages a server with custom loottables for different tiers.

**Comment by baruchvlz** [comment]
@virtualbjorn Well, as I [already said](https://github.com/OhhLoz/HoneyPlus/issues/12#issuecomment-863072582) this is possible via RPC relays. So feel free to give it a go if you want or wait until Loz adds it. Given your attitude, I do not wish to do this myself.

**Comment by virtualbjorn** [comment]
I'm just stating the scenario, not sure why you're getting your ego poked. When I just proved you wrong. That's why its good to add words that states youi're not sure or you have to check. And you just straight up shoot my suggestion down by saying EpicLoot doesn't do it when I just gave the example by experience. :)

**Comment by baruchvlz** [comment]
> you just straight up shoot my suggestion down

[I did](https://github.com/OhhLoz/HoneyPlus/issues/12#issuecomment-862305432)? [Did I know](https://github.com/OhhLoz/HoneyPlus/issues/12#issuecomment-863072582)? Odd.

**Comment by virtualbjorn** [comment]
🤷I suggested because I'm not a C# developer. 😊 Well, hopefully it will get integrated.

**Comment by baruchvlz** [comment]
@virtualbjorn instarted working on this and then it hit me... why is the server sync needed? The only thing you could potentially change is the material cost of the recipes, but the health/ stamina gain is in the asset themselves.
