### ISSUE TITLE
Honey Plus Issue

### ISSUE THREAD

**Issue by AJ1Stone** [OhhLoz/HoneyPlus#14]
Today I did the update to your mod and I am getting the following error:

[Info   :   BepInEx] Loading [HoneyPlus 2.0.2]
[Error  :Jotunn.Utils.AssetUtils] Error, failed to load contents from non-existant path: $C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\plugins\OhhLoz-HoneyPlus\recipes.json
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HoneyPlus.HoneyPlus.AddCustomItems () (at <ff2668d1e47346049453724253c8a569>:0)
HoneyPlus.HoneyPlus.Awake () (at <ff2668d1e47346049453724253c8a569>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by OhhLoz** [comment]
Hi,

If you're installing manually it needs to be in a folder called "OhhLoz-HoneyPlus" as that is the format that Thunderstore uses.
Ill update the readme.

**Comment by AJ1Stone** [comment]
Yes, Ive been using the mod for awhile now, it just started after I did the update. 
A few other mod devs looked at it and said to reach out to you because there should be no reason I am getting the error, it is the only error I have.

**Comment by AJ1Stone** [comment]
Ahhhhh, yes, I had it named HoneyPlus all this time and it always worked. Then after the update I was receiving the error. But, I just renamed it as you said OhhLoz-HoneyPlus and now its working and no errors. Thanks!
