### ISSUE TITLE
Update request and addition?

### ISSUE THREAD

**Issue by ValkierCS** [OhhLoz/HoneyPlus#16]
My husband and I Love this Mod, we tend to find a lot of bees and not a lot of use for Honey, This is a brilliant MOD, but it could use a more recent update.
One thing I would like to recommend is that one or two recipes be added that do not require a cauldron to make.

**Comment by OhhLoz** [comment]
Hi thanks for the kind words, im glad you like it!.
It's been quite a while since I've worked on this mod so I'll need to familiarise myself with it again. 
AFAIK it needed an update a long time ago so I'm surprised it even still works.

**Comment by OhhLoz** [comment]
Hi, Apologies it took so long, it wouldn't function for so long, it should work for now with 2 new items in version 2.0.3
