### ISSUE TITLE
Perhaps tweak values or rethink what the purpose of the honey should be

### ISSUE THREAD

**Issue by OhhLoz** [OhhLoz/HoneyPlus#2]
At the moment it is 5hp & 5 stamina boost to the base food items.
It could increase duration, or hp regen.
Maybe even add a new effect that gives you a speed boost when eating the base honey

**Comment by thenaptaker** [comment]
Agreed. I think the honey food items could keep with the spirit of why Honey is such a good food itself, the 5hp/s being the highest hp/s food in the game.

**Comment by OhhLoz** [comment]
> Agreed. I think the honey food items could keep with the spirit of why Honey is such a good food itself, the 5hp/s being the highest hp/s food in the game.
> 
> Edit: Honey Sweetened Sausages using 4 sausages and 12 honey for just one food item is pretty bad.

Yea I probably will change the HP regen. The sausages should give you 4 back so thats an error in the recipe not intentional
