### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by theernestrain** [OhhLoz/HoneyPlus#20]
[Error  :Jotunn.Utils.AssetUtils] Error, failed to load contents from non-existant path: $C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\plugins\OhhLoz-HoneyPlus\recipes.json
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HoneyPlus.HoneyPlus.AddCustomItems () (at <2c48465be1b74b8f956f9bb6bd90babe>:0)
HoneyPlus.HoneyPlus.Awake () (at <2c48465be1b74b8f956f9bb6bd90babe>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

am i installing wrong?

**Comment by OhhLoz** [comment]
Apologies, I must've changed the way I formatted the zip releases here as the instructions for manual installation on the readme aren't correct anymore. 

The contents of the "files" folder inside the zip need to be extracted to the "OhhLoz-HoneyPlus" folder.

I don't use manual installation so I overlooked this so thanks for bringing this to my attention.

**Comment by theernestrain** [comment]
Thanks so much for the clarification. I love your work btw. Keep it up!

**Comment by OhhLoz** [comment]
Thanks very much, hopefully I can add alot more content from the mistlands (although I can't unpack the game at the moment)
