### ISSUE TITLE
HoneyPlus Error InGame - Mistlands Modded

### ISSUE THREAD

**Issue by J0HNN1E** [OhhLoz/HoneyPlus#22]
Issue InGame : HoneyPlus

Image : https://ibb.co/CVTWB5Z

Thanks for your work!!
![honeyplus_error](https://user-images.githubusercontent.com/76440328/208109494-a219717b-ed74-472a-8741-f0c7dfc455dc.png)

**Comment by OhhLoz** [comment]
I take it this happens on loading the game? Does it happen every time? Do you have EpicLoot? 

The console printout would help to see at what point the error is thrown, as there are printouts at different parts of execution of the code.

**Comment by J0HNN1E** [comment]
Nop we are using Jewelcrafting on the latest version (Mistlands) + Soulcatcher Additions (in order to add more gems / souls)
Sure I'll post my logs a bit later, I'll edit this message.

Yes it happens everytime, but I noticied a changed I've made : I renamed the mod folder OhhLoz-HoneyPlus-vX.X.X instead of OhhLoz-HoneyPlus

Maybe this causes this error, maybe?
Thanks for your work.

----------------------------------------------------

EDIT INCOMING (with logs)

**Comment by OhhLoz** [comment]
Yea the folder needs to be "OhhLoz-HoneyPlus" for the mod to work, at least currently

**Comment by J0HNN1E** [comment]
Ok I'll give a try and upload logs.

**Comment by OhhLoz** [comment]
Closing as instructions are now present on the thunderstore for manual installation
