### ISSUE TITLE
New food item

### ISSUE THREAD

**Issue by Killface212** [OhhLoz/HoneyPlus#23]
Honey glazed, magecap stuffed jotin puffs

2 honey 3 magecap 3 join puff makes 3, the could come with benefit of eitr maybe 1.5x cap amount as a in recipe bonus

**Comment by OhhLoz** [comment]
Thanks for the recommendation, sounds like a good idea. I've only just gotten to the Mistlands on my playthrough so I was hesitant adding things with eitr for balance reasons but I will do in the near future.

**Comment by OhhLoz** [comment]
Added in a modified capacity in 3.0.4, thanks for the suggestion
