### ISSUE TITLE
EpicLoot interaction

### ISSUE THREAD

**Issue by Devestatio** [OhhLoz/HoneyPlus#26]
Not sure which side is causing the problem, but posting to both to see who can fix it, this is being spammed non stop.

"[Warning: Epic Loot] Tried to get element for $custom_item_honeyneckjerky at 5,6, but element was null (total elements = 2)
[Warning: Epic Loot] Tried to get element for $custom_item_honeydeerjerky at 6,6, but element was null (total elements = 2)
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterUI.GameClasses.BetterHotkeyBar.PatchHotkeyBar (HotkeyBar& __instance, Player& player) (at <782a6fbf20064a6bb00c8bb10338286a>:0)
(wrapper dynamic-method) HotkeyBar.DMD<HotkeyBar::UpdateIcons>(HotkeyBar,Player)
HotkeyBar.Update () (at <035307060cbb4b30b916cd82ebd80490>:0)"

**Comment by OhhLoz** [comment]
Do you know if this affects the functionality or is cosmetic?
I'm not sure what Epic Loot is trying to fetch from the items.
The stack trace seems to be referring to BetterUI, are you using the updated [BetterUI_Reforged](https://valheim.thunderstore.io/package/thedefside/BetterUI_Reforged/)?

**Comment by Devestatio** [comment]
Sorry for the late response, I was very distracted today. But yes I am using BetterUI_Reforged, and that extra equipment and hotkey slots is what was causing the issue. I disabled them in the config, and I no longer got errors. Still odd that the specific interaction error did not occur until I dropped EpicLoot into the mix. Not sure what exactly is causing the issue specifically, just that with all three put in together I get the error.

And I was still able to continue playing, I just had the constant error spam that was causing lag for me. It might all be on EL's end, as I have since run into 2 new major errors as well being caused by EL's interaction with BetterUI and extended inventories.

**Comment by OhhLoz** [comment]
Thats strange, I use both BetterUI_Reforged and HoneyPlus without errors. It must be some weird combination with EpicLoot thrown in the mix like you said. Its a shame since those hotkeys are really handy.

**Comment by Devestatio** [comment]
Yea it was working without issue before I had EpicLoot, so It has to be on that mod causing the issue, unfortunately I haven't gotten a response at all in that Discord or from Randy's Git, so it's up in the air. I will go ahead and close this here on your end, since I am sure now, that it's not an issue caused by your mod. Thanks for looking into it and your hard work on the mod.

**Comment by OhhLoz** [comment]
> Yea it was working without issue before I had EpicLoot, so It has to be on that mod causing the issue, unfortunately I haven't gotten a response at all in that Discord or from Randy's Git, so it's up in the air. I will go ahead and close this here on your end, since I am sure now, that it's not an issue caused by your mod. Thanks for looking into it and your hard work on the mod.

Thanks for trying
