### ISSUE TITLE
Shaders from mistlands game rip don't load correctly, displaying a warning in console

### ISSUE THREAD

**Issue by OhhLoz** [OhhLoz/HoneyPlus#27]
This is prevalent in the new Mushroom Stew.

[Warning: Unity Log] Failed to find expected binary shader data in 'Custom/Vegetation'.

It appears to just be cosmetic

**Comment by Agileone2** [comment]
Hello,

I do believe this is from "HoneyCookedSeeker" also?

![image](https://user-images.githubusercontent.com/120989497/208319855-90efd2f3-4325-4617-afc5-f577902248c4.png)

**Comment by MSchmoecker** [comment]
This is because the ripped shaders, even the new yaml ones, are non-functional and you have to replace them with the real ingame shaders. This can be done manually or since you are already using JVL with [Mocked Shaders](https://valheim-modding.github.io/Jotunn/tutorials/asset-mocking.html#shader-mocking)

**Comment by OhhLoz** [comment]
> This is because the ripped shaders, even the new yaml ones, are non-functional and you have to replace them with the real ingame shaders. This can be done manually or since you are already using JVL with [Mocked Shaders](https://valheim-modding.github.io/Jotunn/tutorials/asset-mocking.html#shader-mocking)

Thanks, I knew it was because of the ripped shaders but I didn't know JVL had a way around it, thanks for the link :)

**Comment by OhhLoz** [comment]
> I do believe this is from "HoneyCookedSeeker" also?

Hi, no the Seeker shaders are fine it's from the Mushroom Stew only, the errors appear before the Loading of HoneyMushroomStew

**Comment by OhhLoz** [comment]
Fixed in 3.0.8
