### ISSUE TITLE
Food suggestion

### ISSUE THREAD

**Issue by Killface212** [OhhLoz/HoneyPlus#28]
Another food suggestion for mistlands stuff, mushroom & lox pie, maybe 1 less loc meat but 1 of each 3 mushrooms and some honey, (needing to be baked in oven) in the use case same ish stat's as loc pie but with some eitr gen, for battle makes, high hp,stam but low eitr for defensive magic

**Comment by OhhLoz** [comment]
Thanks for the suggestion, I've wanted to add things to do with the oven so this is a good idea. I'll likely change the lox meat for hare meat

**Comment by Killface212** [comment]
That's good, forgot about hare meat

**Comment by Killface212** [comment]
Another idea if you were wanting to add more oven stuff would be carrot cake, seeing they added eggs, eggs flower carrots and some honey (as a sugar replacement) ? Would be a end of plains/mistlands item (eggs require yag to be killed)

**Comment by Killface212** [comment]
Could also do blueberry muffins for oven food, have as good stam food like eyescream.

**Comment by OhhLoz** [comment]
All good ideas thanks

**Comment by Killface212** [comment]
Sorry for the suggestion spam, I'm at work board out of my mind with nothing to do and ideas just pop in

**Comment by OhhLoz** [comment]
No problem I appreciate the input

**Comment by OhhLoz** [comment]
Hare Pie & Carrot cake added in 4.0.0, thanks!
