### ISSUE TITLE
Unable to update Mod for my server

### ISSUE THREAD

**Issue by NanakoMiko** [OhhLoz/HoneyPlus#30]
Hi 
Hope you can help.
I have Honey Plus 3.1.0 installed on my server and on client, if i update it on client side and server i still get a error when login in the server requesting that the mod be downgraded to 3.1.0.

I will appreciate if you are able to help thanks

**Comment by OhhLoz** [comment]
Hi,
Do you mean you have 3.2.0 on both client and server but it still tells you to downgrade to 3.1.0? If that's happening then something's gone wrong. I recommend using 3.1.0 in the meantime if that works, I can't really fix as I'm away for Christmas but I can try.

**Comment by NanakoMiko** [comment]
yea on both, no rush. I updated it on both the client and server but still get an error that the server is on version 3.1.0 , i dropped the updated dll under the bepinex/plugins on the server. And Merry Christmas and Happy New Year :)

**Comment by OhhLoz** [comment]
> yea on both, no rush. I updated it on both the client and server but still get an error that the server is on version 3.1.0 , i dropped the updated dll under the bepinex/plugins on the server. And Merry Christmas and Happy New Year :)

Damn that's annoying, it should be an easy fix which makes it more frustrating that I can't do it atm. Merry Christmas & happy new year!

**Comment by OhhLoz** [comment]
I can't reproduce the issue as the version number is correct in both the .dll and the manifest.json

**Comment by NanakoMiko** [comment]
Thanks, I managed to get it sorted somehow.

You can close the request.

Regards/Groete,
Christiaan Jacobsz
