### ISSUE TITLE
Issues with cooked honey.

### ISSUE THREAD

**Issue by AgentX2006** [OhhLoz/HoneyPlus#31]
1. It is only able to be cooked on the wooden cooking station and not it's upgraded form the iron cooking station.
2. There is no graphic/sound when honey is placed on the cooking station. It is only visible after fully cooking.

**Comment by OhhLoz** [comment]
Thanks for letting me know.
The first is an oversight so should be easy, the second I thought I had fixed but seems to have resurfaced on release. 
Quite annoying

**Comment by OhhLoz** [comment]
As of 5.1.0 issue 2 is fixed however issue 1 persists, I feel that pushing a release now before fixing issue 1 is preferable as issue 2 causes fps drops, console errors & confusion
