### ISSUE TITLE
Issue with Seared Honeycomb

### ISSUE THREAD

**Issue by MrSuperPhreak** [OhhLoz/HoneyPlus#34]
The expiration of the "Sugar Rush" effect causes a loss of player control due to a repeated error where the mod uses a dated clear effect command (statuseffect.removestarteffects).

**Comment by OhhLoz** [comment]
Wow that's really problematic, thanks for telling me. It uses a vanilla effect as a template so perhaps something got wiped when it was adapted to the Honey.

**Comment by MrSuperPhreak** [comment]
Of course! Can replicate/provide specific log data if needed. Thanks for all your work, love the mod!

**Comment by OhhLoz** [comment]
It was an issue with Jotunn mocking the start effects, I've removed them for now and updating the mod now. Thanks for the kind words :)
