### ISSUE TITLE
Internal IDs for modded food

### ISSUE THREAD

**Issue by BlackDogTM** [OhhLoz/HoneyPlus#35]
Hello,

first of all thank you for your great mod. I really enjoy the playthrough with honeyplus. It revives my most beloved food - honey - back to new heights. H&H kinda messed up honey. 

My question is if you could provide the Internal IDs for all the modded foods or tell me where I can find them, because I'd like to change some recipes of other foods (i.e. wolf skewer) to be craftable with honey marinated wolf meat. To do this I installed another mod that allows editing the crafting requirements and stats of food items but without the internal IDs of your custom Items I just doesn't work. I trief guessing my best but I just couldn't find it out. 

Thanks in advance!

**Comment by OhhLoz** [comment]
Hey,

Thanks for the compliments, I hadn't updated the mod for a year and H&H made this mod super overpowered. It removed the unique thing about honey giving extra regen as far as I can remember.

Theres a couple of ways of getting the internal IDs.
You could look through the [recipes.json](https://github.com/OhhLoz/HoneyPlus/blob/master/HoneyPlus/recipes.json) and the internal IDs are under the "Item" field, or an easier way would be to look in the [prefab](https://github.com/OhhLoz/HoneyPlus/tree/master/HoneyPlusUnity/Prefabs) folder and the names of the .prefabs are the internal IDs.

**Comment by BlackDogTM** [comment]
yes, they removed the health regen advantages of honey... however

thank you! this helps me quite a lot :)

have a nice day

**Comment by OhhLoz** [comment]
No problem, you too! :)
