### ISSUE TITLE
Honey Sausage x4 Recipe

### ISSUE THREAD

**Issue by mjbrown3** [OhhLoz/HoneyPlus#36]
You only need 1 sausage to make 4 honey sausages, Just wanted to let you know

**Comment by OhhLoz** [comment]
That's weird, when I tested it looks like this. Does yours show differently? 
![image](https://user-images.githubusercontent.com/22823143/218291248-5abc6db2-b265-475d-824f-0eac71da25eb.png)

**Comment by mjbrown3** [comment]
This is what im getting, maybe is a conflicting mod? The tar is right but the royal Jelly is also the same as the 1x

<img width="597" alt="image" src="https://user-images.githubusercontent.com/125170103/218317511-c8545b83-0259-4dd7-8290-44abe918323e.png">

<img width="602" alt="image" src="https://user-images.githubusercontent.com/125170103/218317609-7baabb44-1e05-44aa-9d6f-c2b387addcb4.png">

**Comment by OhhLoz** [comment]
I'm not sure what could be causing that, perhaps the multicraft mod? I tested it again on my full modded character and couldn't reproduce it. Do you have Epic Loot? That has caused some conflict issues in the past

**Comment by mjbrown3** [comment]
We do use epic loot, maybe we just need to delete and recreate the config?

**Comment by OhhLoz** [comment]
I added Epic Loot to my test character and the recipes show up normally so either it could be the config like you suggest or another mod
