### ISSUE TITLE
Unable to stack the items

### ISSUE THREAD

**Issue by FIKUFIKS** [OhhLoz/HoneyPlus#38]
Same items made on different crafting stations will not stack. For example deer jerky crafted using your basic inventory will not stack with deer jerky crafted on a workbench, instead you will get an error:
[Error : Unity Log] MissingMethodException: bool
UIGroupHandler.IsActive()
Stack trace:

(Im not sure if that error is related)

**Comment by OhhLoz** [comment]
Thanks for the report, that's super weird. I can't think of any reason off the top of my head. They should definitely be stackable as they are the same item whether they were made in the workbench or in the hand crafting.

**Comment by OhhLoz** [comment]
Hey, I just tested all the jerkies and they work fine on my end. I tested them being crafted in both workbench and hand crafting and they stacked, even if I cleared my inventory between by dropping them on the floor they still stacked. Perhaps there is another mod conflicting?

**Comment by FIKUFIKS** [comment]
Yes, I'm sorry for the confusion, its not a mod conflict it was the "Cooking" mod that adds a cooking skill. Sorry for taking a long time to reply.

**Comment by OhhLoz** [comment]
No problem
