### ISSUE TITLE
Can't move Jerkies to the Cauldron

### ISSUE THREAD

**Issue by BoildownAH** [OhhLoz/HoneyPlus#40]
The configuration options to move the jerkies (both vanilla and added by this mod) don't work. They stay in hand-crafting. Not talking about the option to move _every_ recipe to the cauldron option (I haven't tested that), but just the two options to move the vanilla jerkies and the jerkies added by HoneyPlus.

Using 5.3.0 and a client on a dedicated server. The config options were set on the server.

**Comment by OhhLoz** [comment]
Hi I just tested after reinstalling and it works for me.
Do your settings look like this?
![image](https://github.com/OhhLoz/HoneyPlus/assets/22823143/ff52b778-56a7-4c20-a110-ce45edc30878)
Also the settings need to match on both the client and the server side to function correctly

**Comment by BoildownAH** [comment]
On my client they're reversed. So its the client config that's doing it then. Is there way to enforce the server config on the clients?

**Comment by BoildownAH** [comment]
Additionally the jerky recipes are available on the workbench...

**Comment by OhhLoz** [comment]
All of the config settings have flags `IsAdminOnly = true` which should prevent non admins from changing them and will automatically match with the server. [As described here](https://valheim-modding.github.io/Jotunn/tutorials/config.html)

**Comment by BoildownAH** [comment]
Haven't been able to get that to work. I removed myself from the adminlist and tried adding

IsAdminOnly = true

and also

AdminOnly = true

To the config file, but the config on the server hasn't been enforced on my client.

**Comment by OhhLoz** [comment]
I'm saying you shouldn't need to add it, it's already present in the code and should automatically do everything for you. 
![image](https://github.com/OhhLoz/HoneyPlus/assets/22823143/786cf91e-32f2-40b8-8bbd-ec7d3f494839)
I'm guessing you have Jotunn and BepInEx otherwise I don't think you would see any recipes. 
There could be other mod conflicts however thats unlikely. Its possible BepInEx/Jotunn have updated how they handle these things

**Comment by BoildownAH** [comment]
I do have Jotunn and BepInEx.

Hmm I don't know then. Its not a big deal so I'll just deal with it I guess.

**Comment by BoildownAH** [comment]
I just realized I should mention here my solution to this problem. I ended up pushing the config file to clients by putting it in the BepInEx\config folder of the modpack I'm using.

**Comment by OhhLoz** [comment]
damn it should've done that for you
