### ISSUE TITLE
New Patch Compatibility

### ISSUE THREAD

**Issue by BoildownAH** [OhhLoz/HoneyPlus#42]
Valheim released a new patch (0.217.22 and its hotfix 0.217.24) that broke practically all mods that interact with text in the game, and probably other things besides. I believe that applies to HoneyPlus. Is there an ETA for when HoneyPlus will be updated to be compatible with this patch?

Thanks!

**Comment by BoildownAH** [comment]
Update: In limited testing the old version still seems to work. Certainly doesn't crash the client like other mods. So this mod might be fine, but you might consider doing a "courtesy patch" lest people be afraid to use it, because something like 70% of all mods broke in the this Valheim update, and the advice being thrown around is to remove all mods that haven't been updated since October 5th.

**Comment by OhhLoz** [comment]
Ah ok thanks for the heads up
