### ISSUE TITLE
No Recipes After Update

### ISSUE THREAD

**Issue by mdrain18** [OhhLoz/HoneyPlus#47]
After this latest update, my char cant make anything on the Apiary because there doesnt seem to be any recipes. 
Not sure what could be causing it.

**Comment by mdrain18** [comment]
![Capture](https://github.com/OhhLoz/HoneyPlus/assets/3029865/583d636a-0ba2-486b-89b8-0c97e2ae124d)
Here is a screenshot of what I'm seeing.

**Comment by Nsgtr88** [comment]
I am also having the same issue! I tried to install an older outdated version. Did not work either. I hope they fix this fast, I like this mod.

**Comment by jneb802** [comment]
I am also experiencing this issue. 

I am able to solve the issue by downgrading the Jotunn mod to version 2.19.1.

**Comment by OhhLoz** [comment]
After speaking with one of the Jötunn devs It's an issue with the workstation not being resolved correctly, they said they are working on a fix so the only workaround atm is to downgrade and use a previous version

**Comment by OhhLoz** [comment]
Fixed in newest Jötunn
