### ISSUE TITLE
Enhancements for Ashlands

### ISSUE THREAD

**Issue by dreamdenizen** [OhhLoz/HoneyPlus#49]
My group and I are huge fans of your mod and would love to see it enhanced to include the Ashlands ingredients.

**Comment by mjbrown3** [comment]
I second this, We started a fresh playthrough for the Ashlands update and are happy its still working. would love some additions once we get to the ashlands

**Comment by Fourmiant** [comment]
No idea is the mod owner is still around, if as a suggestion, the next upgrade could be a small Uncapping Table (with or without cover), using mainly Flametal as a component, and possibly requiring Ashwood, Pot shard and Molten Cores.

**Comment by OhhLoz** [comment]
Preliminary Ashland's update is out, thanks for using my mod!
