### ISSUE TITLE
[Request] Compatibility with Stamina Regeneration from Food mod

### ISSUE THREAD

**Issue by greenskye** [OhhLoz/HoneyPlus#5]
Any chance you could work to be compatible with [Stamina Regeneration from Food](https://www.nexusmods.com/valheim/mods/431) mod? Currently Honey+ doesn't seem to get stamina regen from that mod. The mod author has already tried moving the load order to the end, but it still didn't work. If you could take a look that would be amazing!

**Comment by OhhLoz** [comment]
I'll look into it, thanks for your interest in my mod

**Comment by OhhLoz** [comment]
This might work now with version 2.0.0. I'll try to test it when I can
