### ISSUE TITLE
Possible migration to JotunnLib instead of current method using ValheimLib

### ISSUE THREAD

**Issue by OhhLoz** [OhhLoz/HoneyPlus#7]

**Comment by whisk420** [comment]
https://github.com/Valheim-Modding/Jotunn
JotunnLib and ValheimLib have been merged into Jotunn as of today/yesterday and are both being depricated. I hope to see this mod continue to live and be updated accordingly.

**Comment by OhhLoz** [comment]
> https://github.com/Valheim-Modding/Jotunn
> JotunnLib and ValheimLib have been merged into Jotunn as of today/yesterday and are both being depricated. I hope to see this mod continue to live and be updated accordingly.

Hey thanks for the heads up, I saw they were merging I just didn't remember when. I'll most likely migrate this mod to the newly merged framework

**Comment by baruchvlz** [comment]
#9 here it is

**Comment by baruchvlz** [comment]
I took the liberty of doing this because I want to use the mod. The PR is open if you wish to merge it. (#9)

**Comment by OhhLoz** [comment]
Added in v2.0.0
Thanks @baruchvlz
